mysite/homepage/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'homepage'

urlpatterns = [
    url(r'^$', views.login_view, name="login"),
    url(r'^compose/$', views.compose_view, name="compose"),
    url(r'^inbox/$', views.inbox_view, name="inbox"),
    url(r'^sent/$', views.sent_view, name="sent"),
    url(r'^trash/$', views.trash_view, name="trash"),
    url(r'^options/$', views.options_view, name="options")
]

mysite/mysite/homepage/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'homepage'

urlpatterns = [
    url(r'^$', views.login_view, name="login"),
    url(r'^compose/$', views.compose_view, name="compose"),
    url(r'^inbox/$', views.inbox_view, name="inbox"),
    url(r'^sent/$', views.sent_view, name="sent"),
    url(r'^trash/$', views.trash_view, name="trash"),
    url(r'^options/$', views.options_view, name="options")
]

mysite/mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/$', admin.site.urls),
    url(r'^',include('homepage.urls')),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/$', admin.site.urls),
    url(r'^',include('homepage.urls')),
]

mysite/homepage/models.py
from django.db import models

class UserDetails(models.Model):
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=50)

class option(models.Model):
    option = models.CharField(max_length=100)

mysite/mysite/homepage/models.py
from django.db import models

class UserDetails(models.Model):
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=50)

class option(models.Model):
    option = models.CharField(max_length=100)

mysite/homepage/forms.py
from django import forms
from . import models

class UserForm(forms.ModelForm):
    class Meta:
        model = models.UserDetails
        fields = ['email','password']
        widgets = {
        'email' : forms.EmailInput(),
        'password': forms.PasswordInput(),
        }

mysite/mysite/homepage/forms.py
from django import forms
from . import models

class UserForm(forms.ModelForm):
    class Meta:
        model = models.UserDetails
        fields = ['email','password']
        widgets = {
        'email' : forms.EmailInput(),
        'password': forms.PasswordInput(),
        }

mysite/homepage/views.py
from django.shortcuts import render, redirect
from . import forms
import imaplib,email
from gtts import gTTS
import os
from playsound import playsound
from django.http import HttpResponse
import speech_recognition as sr
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from django.http import JsonResponse
import re

file = "good"
i="0"
passwrd = ""
addr = ""
s = smtplib.SMTP('smtp.gmail.com', 587)
s.starttls()
imap_url = 'imap.gmail.com'
conn = imaplib.IMAP4_SSL(imap_url)
attachment_dir = 'C:/Users/mahender/Desktop/minor'

def texttospeech(text, filename):
    filename = filename + '.mp3'
    flag = True
    while flag:
        try:
            tts = gTTS(text=text, lang='en', slow=False)
            tts.save(filename)
            flag = False
        except:
            print('Trying again')
    playsound(filename)
    os.remove(filename)
    return

def speechtotext(duration):
    global i, addr, passwrd
    r = sr.Recognizer()
    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source, duration=1)
        # texttospeech("speak", file + i)
        # i = i + str(1)
        playsound('speak.mp3')
        audio = r.listen(source, phrase_time_limit=duration)
    try:
        response = r.recognize_google(audio)
    except:
        response = 'N'
    return response

def convert_special_char(text):
    temp=text
    special_chars = ['dot','underscore','dollar','hash','star','plus','minus','space','dash']
    for character in special_chars:
        while(True):
            pos=temp.find(character)
            if pos == -1:
                break
            else :
                if character == 'dot':
                    temp=temp.replace('dot','.')
                elif character == 'underscore':
                    temp=temp.replace('underscore','_')
                elif character == 'dollar':
                    temp=temp.replace('dollar','$')
                elif character == 'hash':
                    temp=temp.replace('hash','#')
                elif character == 'star':
                    temp=temp.replace('star','*')
                elif character == 'plus':
                    temp=temp.replace('plus','+')
                elif character == 'minus':
                    temp=temp.replace('minus','-')
                elif character == 'space':
                    temp = temp.replace('space', '')
                elif character == 'dash':
                    temp=temp.replace('dash','-')
    return temp

def login_view(request):
    global i, addr, passwrd
    if request.method == 'POST':
        text1 = "Welcome to our Voice Based Email Portal. Login with your email account to continue. "
        texttospeech(text1, file + i)
        i = i + str(1)

        flag = True
        while (flag):
            texttospeech("Enter your Email", file + i)
            i = i + str(1)
            addr = speechtotext(10)
            if addr != 'N':
                texttospeech("You meant " + addr + " say yes to confirm or no to enter again", file + i)
                i = i + str(1)
                say = speechtotext(3)
                if say == 'yes' or say == 'Yes':
                    flag = False
            else:
                texttospeech("could not understand what you meant:", file + i)
                i = i + str(1)
        addr = addr.strip()
        addr = addr.replace(' ', '')
        addr = addr.lower()
        addr = convert_special_char(addr)

        flag = True
        while (flag):
            texttospeech("Enter your password", file + i)
            i = i + str(1)
            passwrd = speechtotext(10)
            if addr != 'N':
                texttospeech("You meant " + passwrd + " say yes to confirm or no to enter again", file + i)
                i = i + str(1)
                say = speechtotext(3)
                if say == 'yes' or say == 'Yes':
                    flag = False
            else:
                texttospeech("could not understand what you meant:", file + i)
                i = i + str(1)
        passwrd = passwrd.strip()
        passwrd = passwrd.replace(' ', '')
        passwrd = passwrd.lower()
        passwrd = convert_special_char(passwrd)

        imap_url = 'imap.gmail.com'
        # addr = 'rash2801@gmail.com'
        # passwrd = 'rashishreya*01'
        conn = imaplib.IMAP4_SSL(imap_url)
        try:
            conn.login(addr, passwrd)
            s.login(addr, passwrd)
            texttospeech("Congratulations. You have logged in successfully. You will now be redirected to options page.", file + i)
            i = i + str(1)
            return JsonResponse({'result' : 'success'})
        except:
            texttospeech("Invalid Login Details. Please try again.", file + i)
            i = i + str(1)
            return JsonResponse({'result': 'failure'})
    return render(request, 'homepage/home.html')

def options_view(request):
    global i, addr, passwrd
    if request.method == 'POST':
        flag = True
        texttospeech("You are logged into your account. What would you like to do ?", file + i)
        i = i + str(1)
        while(flag):
            texttospeech("To compose an email say compose. To open Inbox folder say Inbox. To open Sent folder say Sent. To open Trash folder say Trash. To Logout say Logout. Do you want me to repeat?", file + i)
            i = i + str(1)
            say = speechtotext(3)
            if say == 'No' or say == 'no':
                flag = False
        texttospeech("Enter your desired action", file + i)
        i = i + str(1)
        act = speechtotext(5)
        act = act.lower()
        if act == 'compose':
            return JsonResponse({'result' : 'compose'})
        elif act == 'inbox':
            return JsonResponse({'result' : 'inbox'})
        elif act == 'sent':
            return JsonResponse({'result' : 'sent'})
        elif act == 'trash':
            return JsonResponse({'result' : 'trash'})
        elif act == 'logout':
            addr = ""
            passwrd = ""
            texttospeech("You have been logged out of your account and now will be redirected back to the login page.",file + i)
            i = i + str(1)
            return JsonResponse({'result': 'logout'})
        else:
            texttospeech("Invalid action. Please try again.", file + i)
            i = i + str(1)
            return JsonResponse({'result': 'failure'})
    elif request.method == 'GET':
        return render(request, 'homepage/options.html')

def compose_view(request):
    global i, addr, passwrd, s
    if request.method == 'POST':
        text1 = "You have reached the page where you can compose and send an email. "
        texttospeech(text1, file + i)
        i = i + str(1)
        flag = True
        flag1 = True
        fromaddr = addr
        toaddr = list()
        while flag1:
            while flag:
                texttospeech("enter receiver's email address:", file + i)
                i = i + str(1)
                to = ""
                to = speechtotext(15)
                if to != 'N':
                    print(to)
                    texttospeech("You meant " + to + " say yes to confirm or no to enter again", file + i)
                    i = i + str(1)
                    say = speechtotext(5)
                    if say == 'yes' or say == 'Yes':
                        toaddr.append(to)
                        flag = False
                else:
                    texttospeech("could not understand what you meant", file + i)
                    i = i + str(1)
            texttospeech("Do you want to enter more recipients ?  Say yes or no.", file + i)
            i = i + str(1)
            say1 = speechtotext(3)
            if say1 == 'No' or say1 == 'no':
                flag1 = False
            flag = True

        newtoaddr = list()
        for item in toaddr:
            item = item.strip()
            item = item.replace(' ', '')
            item = item.lower()
            item = convert_special_char(item)
            newtoaddr.append(item)

        msg = MIMEMultipart()
        msg['From'] = fromaddr
        msg['To'] = ",".join(newtoaddr)
        flag = True
        while (flag):
            texttospeech("enter subject", file + i)
            i = i + str(1)
            subject = speechtotext(10)
            if subject == 'N':
                texttospeech("could not understand what you meant", file + i)
                i = i + str(1)
            else:
                flag = False
        msg['Subject'] = subject
        flag = True
        while flag:
            texttospeech("enter body of the mail", file + i)
            i = i + str(1)
            body = speechtotext(20)
            if body == 'N':
                texttospeech("could not understand what you meant", file + i)
                i = i + str(1)
            else:
                flag = False

        msg.attach(MIMEText(body, 'plain'))
        texttospeech("any attachment? say yes or no", file + i)
        i = i + str(1)
        x = speechtotext(3)
        x = x.lower()
        if x == 'yes':
            texttospeech("Do you want to record an audio and send as an attachment?", file + i)
            i = i + str(1)
            say = speechtotext(2)
            say = say.lower()
            if say == 'yes':
                texttospeech("Enter filename.", file + i)
                i = i + str(1)
                filename = speechtotext(5)
                filename = filename.lower()
                filename = filename + '.mp3'
                filename = filename.replace(' ', '')
                print(filename)
                texttospeech("Enter your audio message.", file + i)
                i = i + str(1)
                audio_msg = speechtotext(10)
                flagconf = True
                while flagconf:
                    try:
                        tts = gTTS(text=audio_msg, lang='en', slow=False)

mysite/mysite/homepage/templates/homepage/compose.html
{% extends 'base_layout.html' %}

{% block content %}
<body onmousedown = "WhichButtonCompose(event)">
<font color="white">
<div class="any">
<h1> COMPOSE</h1><br>
<h3> You have reached the page where you can compose and send an email. </h3>
<script>
	function WhichButtonCompose(event){
		$.ajax({
        url: "{% url 'homepage:compose' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'failure'){
				window.location = "{% url 'homepage:compose' %}";
			}
        }
    });
	}
</script>
{% endblock %}

mysite/mysite/homepage/templates/homepage/home.html
{% extends 'base_layout.html' %}

{% block content %}
    <body onmousedown = "SendPostRequestHome(event)">
	<font color="white">
	<div class="any">
	<center>
	<br><b><u><h1 class="display-3 font-weight-bold"> Welcome To Our Voice Based Email Portal! </h1> 
	</u></b><br>
	<br><br><h1 class="display-4" >Our Team :</h1><br>
	<ul style="list-style-type:none; font-size:24px;">
	<li>RASHI DIXIT</li>
	<li>SHRADHA AGARWAL</li>
	<li>SHREYA MADAAN</li>
	<li>SHORYA KAUSHIK</li>
	</ul>
	<br><br><br>
	<h1 class="display-2 font-weight-bold" style="font-size:30px;">Let's Start ...</h1>
	</center>
	</font>
	<!--<div class="page">
		<h2>Log In</h2>
		<form class="site-form" action="{% url 'homepage:login' %}" method="post">
			{% csrf_token %}
			{% for field in form %}
				<div class="col-sm-6">
					{{ field.label_tag }} - {{ field }}
				</div>
			{% endfor %}
			<input type="submit" value="Login">
		</form>
	</div>-->
	
	<script>
	function SendPostRequestHome(event){
		$.ajax({
        url: "{% url 'homepage:login' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
		
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'failure'){
				window.location = "{% url 'homepage:login' %}";
			}
        }
    });
	}
	</script>

{% endblock %}

mysite/mysite/homepage/templates/homepage/inbox.html
{% extends 'base_layout.html' %}

{% block content %}

	<body onmousedown = "SendPostRequestInbox(event)">
	<font color="white">
	<div class="any">
    <h1> You have reached your inbox.	</h1><br>
    <h2> What would you like to do? <h2><br>

	<h4>1. To read unread emails say unread</h4><br>
	<h4>2. To search for a specific email say search</h4><br>
	<h4>3. To go back to the options page say back</h4><br>
	<h4>4. To Logout say Logout</h4><br>
	
	<script>
	function SendPostRequestInbox(event){
		$.ajax({
        url: "{% url 'homepage:inbox' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
        }
    });
	}
	</script>

{% endblock %}

mysite/mysite/homepage/templates/homepage/options.html
{% extends 'base_layout.html' %}

{% block content %}

	<body onmousedown = "SendPostRequestOptions(event)">
	<font color="white">
	<div class="any">
    <h1> You are logged into your account.	</h1><br>
    <h2> What would you like to do? <h2><br>

	<h4>1. To compose an email say Compose</h4><br>
	<h4>2. To open Inbox folder say Inbox</h4><br>
	<h4>3. To open Sent folder say Sent</h4><br>
	<h4>4. To open Trash folder say Trash</h4><br>
	<h4>5. To Logout say Logout</h4><br>
	
	
	<script>
	function SendPostRequestOptions(event){
		$.ajax({
        url: "{% url 'homepage:options' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'compose'){
				window.location = "{% url 'homepage:compose' %}";
			}
			else if(data.result == 'sent'){
				window.location = "{% url 'homepage:sent' %}";
			}	
			else if(data.result == 'inbox'){
				window.location = "{% url 'homepage:inbox' %}";
			}
			else if(data.result == 'trash'){
				window.location = "{% url 'homepage:trash' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
			else if(data.result == 'failure'){
				window.location = "{% url 'homepage:options' %}";
			}
        }
    });
	}
	</script>

{% endblock %}

mysite/mysite/homepage/templates/homepage/sent.html
{% extends 'base_layout.html' %}

{% block content %}
	<body onmousedown = "SendPostRequestSent(event)">
	<font color="white">
	<div class="any">
	<h1> You have reached your Sent Mails folder. </h1><br>
	<h4>1. To search for a specific email say Search</h4><br>
	<h4>2. To go back to the options page say Back</h4><br>
	<h4>3. To Logout say Logout</h4><br>

	<script>
	function SendPostRequestSent(event){
		$.ajax({
        url: "{% url 'homepage:sent' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
        }
    });
	}
	</script>

{% endblock %}

mysite/mysite/homepage/templates/homepage/trash.html
{% extends 'base_layout.html' %}

{% block content %}
	<body onmousedown = "SendPostRequestTrash(event)">
	<font color="white">
	<div class="any">
	<h1> You have reached your Trash folder. </h1><br>
	<h4>1. To search for a specific email say Search</h4><br>
	<h4>2. To go back to the options page say Back</h4><br>
	<h4>3. To Logout say Logout</h4><br>

	<script>
	function SendPostRequestTrash(event){
		$.ajax({
        url: "{% url 'homepage:trash' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
        }
    });
	}
	</script>

{% endblock %}